version: '3.8'

services:
  app:
    build:
      context:  .
      dockerfile: docker/Dockerfile
    container_name: laravel_app
    user: "1000:1000"
    ports:
      - "8079:80"
      - "4443:443"
    volumes:
      - ./:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      PHP_MEMORY_LIMIT: 512M
      PHP_MAX_EXECUTION_TIME: 300

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
